### ISSUE TITLE
cn.hutool.poi.excel.ExcelReader.read.ExcelReader  NullPointerException

### ISSUE THREAD

**Issue by ghostman-git** [looly/hutool#1893]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.14（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
ExcelReader reader = ExcelUtil.getReader(FileUtil.file("D:\\1 - 副本.xls"), "分年度支出计划表");
reader.read((cell, value) -> {
    System.out.print(cell);
    System.out.println(value);
});
```

2. 堆栈信息
![image](https://user-images.githubusercontent.com/13376074/137427159-e2ae986b-f749-4d02-857d-b3ffd33e4572.png)

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by CherryRum** [comment]
1、原因是您生成这份excel，自身出现了一些问题。

下面是问题所在
![image](https://user-images.githubusercontent.com/24296698/137508795-ec850438-9988-4f19-ac92-5aee2c900f90.png)
我手动生成了一个类似你的表格的数据，并且输出
![image](https://user-images.githubusercontent.com/24296698/137509111-8c0205ad-273d-484d-bb0d-4d2725e360f4.png)
可以看到 没有 null 或者 ，

然后您的文件的输出让我感觉到比较奇怪，由于我们知道xlsx（xls）都是压缩包

解压文件后

对比两个sheet 看到了吧 
![image](https://user-images.githubusercontent.com/24296698/137509913-cf2352e9-5b9c-4c84-bc96-53ec62194e96.png)

猜测可能是生成时候多的，毕竟每个单元格都有这个问题。

建议您排查下文件。

当然你手动处理下 null 应该也可以

**Comment by looly** [comment]
看报错行数，应该是Hutool中代码null检查的问题。

```java
row = this.sheet.getRow(y);
```

这句话可能返回null，Hutool没有判断导致的。

5.7.15修复这个问题。

**Comment by looly** [comment]
@CherryRum 他的文件格式是xls，并不是xlsx，所以没有xml吧？

**Comment by CherryRum** [comment]
是的由于我很纠结为啥除了null还有逗号，xls文件太难逆向，所以使用word转换成的xlsx,并且直接使用还是有一些不可见字符，猜测是生成时候写进去的。



---Original---
From: "Golden ***@***.***&gt;
Date: Sat, Oct 16, 2021 00:18 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [dromara/hutool] cn.hutool.poi.excel.ExcelReader.read.ExcelReader  NullPointerException (#1893)




 
@CherryRum 他的文件格式是xls，并不是xlsx，所以没有xml吧？
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CherryRum** [comment]
感觉，不止是这个问题,这个文件你试试直接转成csv也会有多余符号。



---Original---
From: "Golden ***@***.***&gt;
Date: Sat, Oct 16, 2021 00:11 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [dromara/hutool] cn.hutool.poi.excel.ExcelReader.read.ExcelReader  NullPointerException (#1893)




 
看报错行数，应该是Hutool中代码null检查的问题。
 
5.7.15修复这个问题。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by looly** [comment]
@CherryRum 不管了，null检查没加这是事实，加上先修复这个bug再说。

**Comment by CherryRum** [comment]
确实，要检查下，不过估计他还是会有多的字符，老哥早点睡呀。



---Original---
From: "Golden ***@***.***&gt;
Date: Sat, Oct 16, 2021 00:40 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [dromara/hutool] cn.hutool.poi.excel.ExcelReader.read.ExcelReader  NullPointerException (#1893)




 
@CherryRum 不管了，null检查没加这是事实，加上先修复这个bug再说。
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
