### ISSUE TITLE
DateUtil获取自然周不兼容ISO-8601

### ISSUE THREAD

**Issue by wddxshy** [looly/hutool#1988]
1. 复现代码
```java
Calendar calendar = Calendar.getInstance();
        calendar.setMinimalDaysInFirstWeek(4);
        calendar.setFirstDayOfWeek(Calendar.MONDAY);
        calendar.set(2021, Calendar.NOVEMBER,30,0,0);
        System.out.println(calendar.get(Calendar.WEEK_OF_YEAR));
```
以上代码在ISO-8601中算出来的日期2021-11-30是第48周，但是DateUtil获取到的是第49周。
ISO-8601规定，如果1月1日是星期一、星期二、星期三、星期四，那么它是该年的第一周。如果1月1日是星期五、星期六、星期日，它是前一年的第52周或第53周（没有第00周）。12月28日永远在该年的最后一周。而2021年1月1日正好在周五，导致获取的自然周为49周。

通过查看DateUtil.weekOfYear方法，发现并没有设置一年中的第一周需要的最少天数，也就是setMinimalDaysInFirstWeek()方法。
![微信图片_20211130235506](https://user-images.githubusercontent.com/58757625/144081461-936eaa9c-be61-4d36-9d6f-3e487368cdb5.png)
能否做下兼容呢

**Comment by CherryRum** [comment]
https://github.com/dromara/hutool/issues/1237   貌似我提过这样的问题

**Comment by looly** [comment]
@CherryRum 我稍后一起看下这个和你说的有没有区别。

**Comment by CherryRum** [comment]
嗯嗯，刚发现了一个问题，打算和你商量下要不要改。等我睡醒提个pr



---原始邮件---
发件人: "Golden ***@***.***&gt;
发送时间: 2021年12月5日(周日) 晚上11:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dromara/hutool] DateUtil获取自然周不兼容ISO-8601 (Issue #1988)




 
@CherryRum 貌似有点儿区别，我稍后一起看下这个和你说的有没有区别。
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by looly** [comment]
5.7.17在DateTime中增加`setMinimalDaysInFirstWeek`方法，这样就可以：

```java
DateTime.now().setMinimalDaysInFirstWeek(4).weekOfYear();
```
